# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Widget(object):
    def setupUi(self, Widget):
        Widget.setObjectName("Widget")
        Widget.resize(348, 463)
        Widget.setMinimumSize(QtCore.QSize(1, 0))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Window, brush)
        Widget.setPalette(palette)
        Widget.setStyleSheet("")
        self.Forward_button = QtWidgets.QPushButton(parent=Widget)
        self.Forward_button.setGeometry(QtCore.QRect(210, 400, 111, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(31, 27, 22))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(31, 27, 22))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(31, 27, 22))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(31, 27, 22))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(31, 27, 22))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(31, 27, 22))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(31, 27, 22))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(31, 27, 22))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(31, 27, 22))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Window, brush)
        self.Forward_button.setPalette(palette)
        self.Forward_button.setStyleSheet("background: rgb #1f1b16;")
        self.Forward_button.setText("")
        icon = QtGui.QIcon.fromTheme("QIcon::ThemeIcon::MediaSkipForward")
        self.Forward_button.setIcon(icon)
        self.Forward_button.setIconSize(QtCore.QSize(25, 25))
        self.Forward_button.setObjectName("Forward_button")
        self.Backward_button = QtWidgets.QPushButton(parent=Widget)
        self.Backward_button.setGeometry(QtCore.QRect(20, 400, 91, 31))
        self.Backward_button.setStyleSheet("background: rgb #1f1b16;")
        self.Backward_button.setText("")
        icon = QtGui.QIcon.fromTheme("QIcon::ThemeIcon::MediaSkipBackward")
        self.Backward_button.setIcon(icon)
        self.Backward_button.setIconSize(QtCore.QSize(25, 25))
        self.Backward_button.setObjectName("Backward_button")
        self.Play_pause_button = QtWidgets.QPushButton(parent=Widget)
        self.Play_pause_button.setGeometry(QtCore.QRect(120, 400, 81, 31))
        self.Play_pause_button.setAutoFillBackground(False)
        self.Play_pause_button.setStyleSheet("background: rgb #1f1b16;")
        self.Play_pause_button.setText("")
        icon = QtGui.QIcon.fromTheme("QIcon::ThemeIcon::MediaPlaybackStart")
        self.Play_pause_button.setIcon(icon)
        self.Play_pause_button.setIconSize(QtCore.QSize(25, 25))
        self.Play_pause_button.setObjectName("Play_pause_button")
        self.cover_art = QtWidgets.QLabel(parent=Widget)
        self.cover_art.setGeometry(QtCore.QRect(20, 10, 311, 371))
        self.cover_art.setText("")
        self.cover_art.setPixmap(QtGui.QPixmap("C:/Users/Alexg/OneDrive/Documents/TvChannelProject/Music for Project/Screenshot 2024-12-10 004220.jpg"))
        self.cover_art.setScaledContents(False)
        self.cover_art.setObjectName("cover_art")

        self.retranslateUi(Widget)
        QtCore.QMetaObject.connectSlotsByName(Widget)

    def retranslateUi(self, Widget):
        _translate = QtCore.QCoreApplication.translate
        Widget.setWindowTitle(_translate("Widget", "Widget"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Widget = QtWidgets.QWidget()
    ui = Ui_Widget()
    ui.setupUi(Widget)
    Widget.show()
    sys.exit(app.exec())
